percept(Log) :-
  [
    {coord:[0,6], walls:["west"], dirt:null, agent:{id:"9af04778-08d6-4e40-8c6f-ba123d292a22", colour:"orange"}},
    {coord:[1,6], walls:[], dirt:null, agent:null},
    {coord:[2,6], walls:[], dirt:null, agent:null},
    {coord:[0,7], walls:["south","west"], dirt:null, agent:null},
    {coord:[1,7], walls:["south"], dirt:null, agent:null},
    {coord:[2,7], walls:["south"], dirt:null, agent:null},
    {coord:[0,5], walls:["west"], dirt:null, agent:{id:"9af04778-08d6-4e40-8c6f-ba123d292a22", colour:"orange"}},
    {coord:[1,5], walls:[], dirt:null, agent:null},
    {coord:[2,5], walls:[], dirt:null, agent:null},
    {coord:[0,4], walls:["west"], dirt:null, agent:null},
    {coord:[1,4], walls:[], dirt:null, agent:null},
    {coord:[2,4], walls:[], dirt:null, agent:null},
    {coord:[0,3], walls:["west"], dirt:null, agent:{id:"9af04778-08d6-4e40-8c6f-ba123d292a22", colour:"orange"}},
    {coord:[1,3], walls:[], dirt:null, agent:null},
    {coord:[2,3], walls:[], dirt:null, agent:null},
    {coord:[0,2], walls:["west"], dirt:null, agent:null},
    {coord:[1,2], walls:[], dirt:null, agent:null},
    {coord:[2,2], walls:[], dirt:null, agent:null},
    {coord:[0,1], walls:["west"], dirt:null, agent:null},
    {coord:[1,1], walls:[], dirt:null, agent:null},
    {coord:[2,1], walls:[], dirt:"orange", agent:null},
    {coord:[0,0], walls:["north","west"], dirt:null, agent:null},
    {coord:[1,0], walls:["north"], dirt:null, agent:null},
    {coord:[2,0], walls:["north"], dirt:null, agent:null},
    {coord:[3,0], walls:["north"], dirt:null, agent:null}
  ].